### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../output/prv32_cpu_min_max/schematics/path0.svg'

### ISSUE THREAD

**Issue by yYaNg0212** [kanndil/interactive_SVG_schematics#3]
use python3 interactiveReport.py -i prv32_cpu_min_max.rpt -s gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00_representations -t opensta
error FileNotFoundError: [Errno 2] No such file or directory: '../output/prv32_cpu_min_max/schematics/path0.svg'

**Comment by kanndil** [comment]
Hi @yYaNg0212, I hope you are finding this repo useful. 

I believe you are passing wrong file pathnames to the Python script. 


For your specific example, you can use the following commands to run the script correctly:

```

cd src/

python3 interactiveReport.py -i ../opensta_reports/prv32_cpu_min_max.rpt -s ../skinFiles/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00_representations/default.svg -t opensta

```


Finally, check the results under the `output` directory

**Comment by kanndil** [comment]
@yYaNg0212 let me know if you still have problems

**Comment by kanndil** [comment]
@yYaNg0212 I closed the issue for now, you can reopen it if you still face the same problem.
